version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] 
      retries: 5
    volumes:
      - dbvolume:/var/lib/mysql
  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app/backend
    depends_on: 
      db:
        condition: service_healthy
    environment:
    - DB_HOST=db
    - DB_USER=root
    - DB_PASSWORD=password
    - DB_DATABASE=development_database
    - DB_PORT=3306
    - PORT=3000

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app/frontend
volumes:
  dbvolume:
